# Generated by Django 2.1.7 on 2019-05-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefits',
            name='employability',
            field=models.FloatField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='energy_savings',
            field=models.FloatField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='externalities',
            field=models.FloatField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='maintenance',
            field=models.FloatField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='value_growth',
            field=models.FloatField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='work_efficiency',
            field=models.FloatField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='costs',
            name='equipment',
            field=models.FloatField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='costs',
            name='management',
            field=models.FloatField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='costs',
            name='reduced_income',
            field=models.FloatField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='b_to_c',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='dpbp',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='irr',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='npv',
            field=models.FloatField(default=0, null=True),
        ),
    ]
