# Generated by Django 2.1.7 on 2019-05-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_remove_social_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='benefits',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='costs',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
