# Generated by Django 2.1.7 on 2019-05-15 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_auto_20190513_1248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Measure',
        ),
    ]
