# Generated by Django 2.1.7 on 2019-05-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_auto_20190523_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='id',
        ),
        migrations.AddField(
            model_name='social',
            name='name',
            field=models.CharField(default=None, max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
