# Generated by Django 2.1.7 on 2019-05-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app2', '0004_delete_measure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity3', models.IntegerField(default=0)),
                ('diesel_oil3', models.IntegerField(default=0)),
                ('motor_gasoline3', models.IntegerField(default=0)),
                ('natural_gas3', models.IntegerField(default=0)),
                ('biomass3', models.IntegerField(default=0)),
                ('electricity7', models.IntegerField(default=0)),
                ('diesel_oil7', models.IntegerField(default=0)),
                ('motor_gasoline7', models.IntegerField(default=0)),
                ('natural_gas7', models.IntegerField(default=0)),
                ('biomass7', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('cost', models.IntegerField()),
                ('lifetime', models.IntegerField()),
                ('description', models.TextField(default=' ')),
                ('category', models.CharField(default=' ', max_length=150)),
                ('measure_type', models.CharField(default=' ', max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
