# Generated by Django 2.1.7 on 2019-05-23 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_auto_20190523_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='measure',
        ),
        migrations.AddField(
            model_name='social',
            name='measure',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app2.Measure'),
        ),
    ]
