# Generated by Django 2.1.7 on 2019-05-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_measure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_savings', models.CharField(default=' ', max_length=150)),
                ('maintenance', models.CharField(default=' ', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(default=' ', max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='measure',
            name='benefits',
            field=models.ManyToManyField(to='app2.Benefits'),
        ),
        migrations.AddField(
            model_name='measure',
            name='costs',
            field=models.ManyToManyField(to='app2.Costs'),
        ),
    ]
