# Generated by Django 2.1.7 on 2019-05-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_auto_20190516_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefits',
            name='employability',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AddField(
            model_name='benefits',
            name='externalities',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AddField(
            model_name='benefits',
            name='value_growth',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AddField(
            model_name='benefits',
            name='work_efficiency',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AddField(
            model_name='costs',
            name='management',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AddField(
            model_name='costs',
            name='reduced_income',
            field=models.CharField(default=' ', max_length=150),
        ),
    ]
