# Generated by Django 2.1.7 on 2019-05-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_auto_20190523_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('name', models.CharField(default=None, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('genre', models.CharField(default=None, max_length=150)),
                ('analysis_pieces', models.CharField(default=None, max_length=300)),
            ],
        ),
    ]
