# Generated by Django 2.1.7 on 2019-05-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_auto_20190516_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.CharField(default=' ', max_length=150)),
                ('benefits', models.ManyToManyField(to='app2.Benefits')),
                ('costs', models.ManyToManyField(to='app2.Costs')),
            ],
        ),
    ]
