# Generated by Django 2.1.7 on 2019-06-04 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Esco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_rate', models.FloatField(default=0.03)),
                ('benefit_share', models.FloatField(default=0, null=True)),
                ('cost_share', models.FloatField(default=0, null=True)),
                ('contract_period', models.IntegerField(default=0, null=True)),
                ('npv', models.FloatField(default=0, null=True)),
                ('b_to_c', models.FloatField(default=0, null=True)),
                ('irr', models.FloatField(default=0, null=True)),
                ('dpbp', models.FloatField(default=0, null=True)),
                ('spbp', models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perspective',
            fields=[
                ('name', models.CharField(default=None, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('discount_rate', models.FloatField(default=0.03)),
                ('analysis_period', models.IntegerField(default=25)),
                ('financial_mechanisms', models.CharField(default=None, max_length=150, null=True)),
                ('costs', models.CharField(default=None, max_length=150, null=True)),
                ('benefits', models.CharField(default=None, max_length=150, null=True)),
                ('npv', models.FloatField(default=0, null=True)),
                ('b_to_c', models.FloatField(default=0, null=True)),
                ('irr', models.FloatField(default=0, null=True)),
                ('dpbp', models.FloatField(default=0, null=True)),
                ('spbp', models.FloatField(default=0, null=True)),
                ('measure', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app2.Measure')),
            ],
        ),
        migrations.AddField(
            model_name='esco',
            name='perspective_analysis',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app2.Perspective'),
        ),
    ]
