# Generated by Django 2.1.7 on 2019-06-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0010_auto_20190609_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefits',
            name='employability',
            field=models.FloatField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='externalities',
            field=models.FloatField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='maintenance',
            field=models.FloatField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='value_growth',
            field=models.FloatField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='work_efficiency',
            field=models.FloatField(default=None, max_length=150, null=True),
        ),
    ]
