# Generated by Django 2.1.7 on 2019-06-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0011_auto_20190609_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefits',
            name='maintenance',
            field=models.FloatField(max_length=150, null=True),
        ),
    ]
