# Generated by Django 2.1.7 on 2019-06-09 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0013_auto_20190609_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='perspective',
            name='time_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='social',
            name='time_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
