# Generated by Django 2.1.7 on 2019-06-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0014_auto_20190609_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='category',
            field=models.CharField(choices=[('industry', 'Industry'), ('household', 'Household-Houses'), ('business', 'Business'), ('private_transport', 'Private Trasport'), ('public_transport', 'Public Transport'), ('public_buildings', 'Public Buildings')], default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='measure',
            name='measure_type',
            field=models.CharField(choices=[('technical', 'Technical'), ('behavioral', 'Behavioral')], default=None, max_length=150),
        ),
    ]
