# Generated by Django 2.1.7 on 2019-06-09 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0015_auto_20190609_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='time_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
