# Generated by Django 2.1.7 on 2019-06-09 21:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0016_portfolio_time_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('name', models.CharField(default=None, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('time_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('costs', models.CharField(default=None, max_length=150, null=True)),
                ('benefits', models.CharField(default=None, max_length=150, null=True)),
                ('discount_rate', models.FloatField(default=0.03)),
                ('analysis_period', models.IntegerField(default=25)),
                ('npv', models.FloatField(default=0, null=True)),
                ('b_to_c', models.FloatField(default=0, null=True)),
                ('irr', models.FloatField(default=0, null=True)),
                ('dpbp', models.FloatField(default=0, null=True)),
                ('measure', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app2.Measure')),
            ],
        ),
    ]
