# Generated by Django 3.0.3 on 2020-03-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0017_financial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Energy_Cost',
            fields=[
                ('energy_type', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('price_with_taxes', models.FloatField(default=0)),
                ('price_without_taxes', models.FloatField(default=0)),
                ('growth_rate', models.FloatField(default=0)),
            ],
        ),
    ]
