# Generated by Django 2.1.7 on 2019-05-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_measure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User1',
        ),
        migrations.AlterField(
            model_name='measure',
            name='biomass',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='measure',
            name='diesel_oil',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='measure',
            name='electricity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='measure',
            name='motor_gasoline',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='measure',
            name='natural_gas',
            field=models.IntegerField(default=0),
        ),
    ]
