# Generated by Django 2.1.7 on 2019-05-16 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0008_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='social',
            name='costs',
        ),
    ]
