# Generated by Django 2.1.7 on 2019-05-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0009_auto_20190516_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='benefits',
            field=models.ManyToManyField(to='app2.Benefits'),
        ),
        migrations.AddField(
            model_name='social',
            name='costs',
            field=models.ManyToManyField(to='app2.Costs'),
        ),
    ]
